/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package score;

import javax.swing.JOptionPane;

/**
 *
 * @author aj
 */
public class Scorecard1 extends javax.swing.JFrame {

    /**
     * Creates new form Scorecard
     */
    public Scorecard1() {
        initComponents();
    }
    public Scorecard1(String B1,String B2, String Bo1) {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Batsman_A = new javax.swing.JLabel();
        Batsman_B = new javax.swing.JLabel();
        Current_run = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        Current_wicket = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Current_over = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Current_balls = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        Dot = new javax.swing.JLabel();
        Run_1 = new javax.swing.JLabel();
        Run_2 = new javax.swing.JLabel();
        Run_3 = new javax.swing.JLabel();
        Run_4 = new javax.swing.JLabel();
        Run_6 = new javax.swing.JLabel();
        Bowled = new javax.swing.JLabel();
        LBW = new javax.swing.JLabel();
        Bye_1 = new javax.swing.JLabel();
        Bye_2 = new javax.swing.JLabel();
        Bye_3 = new javax.swing.JLabel();
        Bye_4 = new javax.swing.JLabel();
        Caught_out = new javax.swing.JLabel();
        LBye_0 = new javax.swing.JLabel();
        LBye_1 = new javax.swing.JLabel();
        LBye_2 = new javax.swing.JLabel();
        LBye_3 = new javax.swing.JLabel();
        LBye_4 = new javax.swing.JLabel();
        Stumped = new javax.swing.JLabel();
        Wide = new javax.swing.JLabel();
        Wide_more = new javax.swing.JLabel();
        Runout = new javax.swing.JLabel();
        NoBall = new javax.swing.JLabel();
        NoBall_more = new javax.swing.JLabel();
        HitWicket = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Save = new javax.swing.JButton();
        jLabel51 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        Bowler_1 = new javax.swing.JLabel();
        Bowler_2 = new javax.swing.JLabel();
        Bowler_3 = new javax.swing.JLabel();
        Bowler_4 = new javax.swing.JLabel();
        Bowler_5 = new javax.swing.JLabel();
        Bowler_6 = new javax.swing.JLabel();
        Bowler_7 = new javax.swing.JLabel();
        Bowler_8 = new javax.swing.JLabel();
        Over_1 = new javax.swing.JLabel();
        RG_1 = new javax.swing.JLabel();
        Wicket_1 = new javax.swing.JLabel();
        Eco_1 = new javax.swing.JLabel();
        Eco_2 = new javax.swing.JLabel();
        Wicket_2 = new javax.swing.JLabel();
        RG_2 = new javax.swing.JLabel();
        Over_2 = new javax.swing.JLabel();
        Over_3 = new javax.swing.JLabel();
        RG_3 = new javax.swing.JLabel();
        Wicket_3 = new javax.swing.JLabel();
        Eco_3 = new javax.swing.JLabel();
        Eco_4 = new javax.swing.JLabel();
        Wicket_4 = new javax.swing.JLabel();
        RG_4 = new javax.swing.JLabel();
        Over_4 = new javax.swing.JLabel();
        Over_5 = new javax.swing.JLabel();
        RG_5 = new javax.swing.JLabel();
        Wicket_5 = new javax.swing.JLabel();
        Eco_5 = new javax.swing.JLabel();
        Eco_6 = new javax.swing.JLabel();
        Wicket_6 = new javax.swing.JLabel();
        RG_6 = new javax.swing.JLabel();
        Over_6 = new javax.swing.JLabel();
        Over_7 = new javax.swing.JLabel();
        Over_8 = new javax.swing.JLabel();
        RG_8 = new javax.swing.JLabel();
        RG_7 = new javax.swing.JLabel();
        Wicket_7 = new javax.swing.JLabel();
        Wicket_8 = new javax.swing.JLabel();
        Eco_7 = new javax.swing.JLabel();
        Eco_8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel50 = new javax.swing.JLabel();
        Batsman_1 = new javax.swing.JLabel();
        Batsman_2 = new javax.swing.JLabel();
        Batsman_3 = new javax.swing.JLabel();
        Batsman_4 = new javax.swing.JLabel();
        Four_1 = new javax.swing.JLabel();
        Six_1 = new javax.swing.JLabel();
        RunS_1 = new javax.swing.JLabel();
        Ball_1 = new javax.swing.JLabel();
        Str_1 = new javax.swing.JLabel();
        Str_2 = new javax.swing.JLabel();
        Str_3 = new javax.swing.JLabel();
        Str_4 = new javax.swing.JLabel();
        Str_5 = new javax.swing.JLabel();
        Str_6 = new javax.swing.JLabel();
        Str_7 = new javax.swing.JLabel();
        Str_8 = new javax.swing.JLabel();
        Str_9 = new javax.swing.JLabel();
        Str_10 = new javax.swing.JLabel();
        Str_11 = new javax.swing.JLabel();
        Ball_11 = new javax.swing.JLabel();
        Ball_10 = new javax.swing.JLabel();
        Ball_9 = new javax.swing.JLabel();
        Ball_8 = new javax.swing.JLabel();
        Ball_7 = new javax.swing.JLabel();
        Ball_6 = new javax.swing.JLabel();
        Ball_5 = new javax.swing.JLabel();
        Ball_4 = new javax.swing.JLabel();
        Ball_3 = new javax.swing.JLabel();
        Ball_2 = new javax.swing.JLabel();
        RunS_2 = new javax.swing.JLabel();
        RunS_3 = new javax.swing.JLabel();
        RunS_4 = new javax.swing.JLabel();
        RunS_5 = new javax.swing.JLabel();
        RunS_6 = new javax.swing.JLabel();
        RunS_7 = new javax.swing.JLabel();
        RunS_8 = new javax.swing.JLabel();
        RunS_9 = new javax.swing.JLabel();
        RunS_10 = new javax.swing.JLabel();
        RunS_11 = new javax.swing.JLabel();
        Six_11 = new javax.swing.JLabel();
        Six_10 = new javax.swing.JLabel();
        Six_9 = new javax.swing.JLabel();
        Six_8 = new javax.swing.JLabel();
        Six_7 = new javax.swing.JLabel();
        Six_6 = new javax.swing.JLabel();
        Six_5 = new javax.swing.JLabel();
        Six_4 = new javax.swing.JLabel();
        Six_3 = new javax.swing.JLabel();
        Six_2 = new javax.swing.JLabel();
        Four_2 = new javax.swing.JLabel();
        Four_3 = new javax.swing.JLabel();
        Four_4 = new javax.swing.JLabel();
        Four_5 = new javax.swing.JLabel();
        Four_6 = new javax.swing.JLabel();
        Four_7 = new javax.swing.JLabel();
        Four_8 = new javax.swing.JLabel();
        Four_9 = new javax.swing.JLabel();
        Four_10 = new javax.swing.JLabel();
        Four_11 = new javax.swing.JLabel();
        Batsman_11 = new javax.swing.JLabel();
        Batsman_10 = new javax.swing.JLabel();
        Batsman_9 = new javax.swing.JLabel();
        Batsman_8 = new javax.swing.JLabel();
        Batsman_7 = new javax.swing.JLabel();
        Batsman_6 = new javax.swing.JLabel();
        Batsman_5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Batsman_A.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        Batsman_A.setText("Player Name");

        Batsman_B.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        Batsman_B.setText("Player Name");

        Current_run.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        Current_run.setText("0");

        jLabel29.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        jLabel29.setText("/");

        Current_wicket.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        Current_wicket.setText("0");

        jLabel31.setText("0");

        jLabel32.setText("Runs in");

        jLabel33.setText("0");

        jLabel34.setText("Photo");
        jLabel34.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel35.setText("Photo");
        jLabel35.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel36.setText("0");

        jLabel37.setText("Runs in");

        jLabel38.setText("0");

        jLabel39.setText("Partnership:-");

        jLabel40.setText("0");

        jLabel41.setText("Runs in");

        jLabel42.setText("0");

        jLabel43.setText("balls");

        jLabel44.setText("Balls");

        jLabel45.setText("Balls");

        jLabel46.setText("*ON STRIKE*");

        jLabel47.setText("*ON STRIKE*");

        jLabel48.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel48.setText("SCORE");

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel1.setText("OVERS:- ");

        Current_over.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        Current_over.setText("0");

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel3.setText(".");

        Current_balls.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        Current_balls.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Batsman_A)
                        .addGap(37, 37, 37)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jLabel39)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel40)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel41)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel42)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel43)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(Current_run, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel29)
                                        .addGap(18, 18, 18)
                                        .addComponent(Current_wicket, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(109, 109, 109)))
                        .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(Current_over)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Current_balls)
                        .addGap(119, 119, 119)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Batsman_B)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel36)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel37)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel45)))))
                .addGap(104, 104, 104))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel44)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel46)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel47)
                        .addGap(127, 127, 127))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel48)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Current_wicket))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Batsman_B)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Current_balls)
                                .addComponent(jLabel3)
                                .addComponent(Current_over)
                                .addComponent(jLabel1))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Current_run)
                            .addComponent(jLabel29))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Batsman_A)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(jLabel32)
                    .addComponent(jLabel33)
                    .addComponent(jLabel36)
                    .addComponent(jLabel37)
                    .addComponent(jLabel38)
                    .addComponent(jLabel44)
                    .addComponent(jLabel45))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel46)
                    .addComponent(jLabel47))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(jLabel40)
                    .addComponent(jLabel41)
                    .addComponent(jLabel42)
                    .addComponent(jLabel43))
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Dot.setText("Dot");
        Dot.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Dot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DotMouseClicked(evt);
            }
        });

        Run_1.setText("1");
        Run_1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Run_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Run_1MouseClicked(evt);
            }
        });

        Run_2.setText("2");
        Run_2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Run_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Run_2MouseClicked(evt);
            }
        });

        Run_3.setText("3");
        Run_3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Run_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Run_3MouseClicked(evt);
            }
        });

        Run_4.setText("4");
        Run_4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Run_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Run_4MouseClicked(evt);
            }
        });

        Run_6.setText("6");
        Run_6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Run_6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Run_6MouseClicked(evt);
            }
        });

        Bowled.setForeground(java.awt.Color.red);
        Bowled.setText("Bowled");
        Bowled.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Bowled.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BowledMouseClicked(evt);
            }
        });

        LBW.setForeground(java.awt.Color.red);
        LBW.setText("LBW");
        LBW.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        LBW.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LBWMouseClicked(evt);
            }
        });

        Bye_1.setText("1 B");
        Bye_1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Bye_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Bye_1MouseClicked(evt);
            }
        });

        Bye_2.setText("2 B");
        Bye_2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Bye_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Bye_2MouseClicked(evt);
            }
        });

        Bye_3.setText("3 B");
        Bye_3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Bye_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Bye_3MouseClicked(evt);
            }
        });

        Bye_4.setText("4 B");
        Bye_4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Bye_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Bye_4MouseClicked(evt);
            }
        });

        Caught_out.setForeground(java.awt.Color.red);
        Caught_out.setText("Caught Out ");
        Caught_out.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Caught_out.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Caught_outMouseClicked(evt);
            }
        });

        LBye_0.setText("L.B");
        LBye_0.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        LBye_0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LBye_0MouseClicked(evt);
            }
        });

        LBye_1.setText("1 L.B");
        LBye_1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        LBye_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LBye_1MouseClicked(evt);
            }
        });

        LBye_2.setText("2 L.B");
        LBye_2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        LBye_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LBye_2MouseClicked(evt);
            }
        });

        LBye_3.setText("3 L.B");
        LBye_3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        LBye_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LBye_3MouseClicked(evt);
            }
        });

        LBye_4.setText("4 L.B");
        LBye_4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        LBye_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LBye_4MouseClicked(evt);
            }
        });

        Stumped.setForeground(java.awt.Color.red);
        Stumped.setText("Stumped");
        Stumped.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Stumped.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StumpedMouseClicked(evt);
            }
        });

        Wide.setForeground(java.awt.Color.blue);
        Wide.setText("Wide only");
        Wide.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Wide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                WideMouseClicked(evt);
            }
        });

        Wide_more.setForeground(java.awt.Color.blue);
        Wide_more.setText("Wide + Others");
        Wide_more.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Wide_more.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Wide_moreMouseClicked(evt);
            }
        });

        Runout.setForeground(java.awt.Color.red);
        Runout.setText("Runout");
        Runout.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Runout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RunoutMouseClicked(evt);
            }
        });

        NoBall.setForeground(java.awt.Color.black);
        NoBall.setText("No Ball only");
        NoBall.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        NoBall.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NoBallMouseClicked(evt);
            }
        });

        NoBall_more.setForeground(java.awt.Color.black);
        NoBall_more.setText("No Ball + More");
        NoBall_more.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        NoBall_more.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NoBall_moreMouseClicked(evt);
            }
        });

        HitWicket.setForeground(java.awt.Color.red);
        HitWicket.setText("Hit Wicket");
        HitWicket.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        HitWicket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HitWicketMouseClicked(evt);
            }
        });

        jButton1.setText("Undo");

        Save.setText("Save & Next Innings");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(Dot, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Run_1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Run_2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(Run_3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(Run_4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(Run_6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(Bowled, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Save))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NoBall, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Wide, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(HitWicket, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Runout, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(LBW, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Bye_1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Bye_2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Bye_3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Bye_4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(LBye_0, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(LBye_1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(LBye_2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(LBye_3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(LBye_4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(NoBall_more, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                                            .addComponent(Wide_more, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(12, 12, 12)))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Stumped, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Caught_out, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE))))
                .addGap(90, 90, 90))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bowled)
                    .addComponent(Run_6)
                    .addComponent(Run_4)
                    .addComponent(Run_3)
                    .addComponent(Run_2)
                    .addComponent(Run_1)
                    .addComponent(Dot))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBW)
                    .addComponent(Bye_1)
                    .addComponent(Bye_2)
                    .addComponent(Bye_3)
                    .addComponent(Bye_4)
                    .addComponent(Caught_out))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Stumped)
                    .addComponent(LBye_4)
                    .addComponent(LBye_3)
                    .addComponent(LBye_2)
                    .addComponent(LBye_1)
                    .addComponent(LBye_0))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Wide)
                    .addComponent(Wide_more)
                    .addComponent(Runout))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HitWicket)
                    .addComponent(NoBall_more)
                    .addComponent(NoBall))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(Save))
                .addGap(24, 24, 24))
        );

        jLabel51.setText("Team 1");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel49.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel49.setText("BOWLING STATS");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Overs", "Runs", "Wicket", "Economy"
            }
        ));
        jScrollPane1.setViewportView(jTable2);

        Bowler_1.setText("Bowler 1");

        Bowler_2.setText("Bowler 2");

        Bowler_3.setText("Bowler 3");

        Bowler_4.setText("Bowler 4");

        Bowler_5.setText("Bowler 5");

        Bowler_6.setText("Bowler 6");

        Bowler_7.setText("Bowler 7");

        Bowler_8.setText("Bowler 8");

        Over_1.setText("0");

        RG_1.setText("0");

        Wicket_1.setText("0");

        Eco_1.setText("0");

        Eco_2.setText("0");

        Wicket_2.setText("0");

        RG_2.setText("0");

        Over_2.setText("0");

        Over_3.setText("0");

        RG_3.setText("0");

        Wicket_3.setText("0");

        Eco_3.setText("0");

        Eco_4.setText("0");

        Wicket_4.setText("0");

        RG_4.setText("0");

        Over_4.setText("0");

        Over_5.setText("0");

        RG_5.setText("0");

        Wicket_5.setText("0");

        Eco_5.setText("0");

        Eco_6.setText("0");

        Wicket_6.setText("0");

        RG_6.setText("0");

        Over_6.setText("0");

        Over_7.setText("0");

        Over_8.setText("0");

        RG_8.setText("0");

        RG_7.setText("0");

        Wicket_7.setText("0");

        Wicket_8.setText("0");

        Eco_7.setText("0");

        Eco_8.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(jLabel49))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Bowler_1)
                            .addComponent(Bowler_3)
                            .addComponent(Bowler_2)
                            .addComponent(Bowler_4)
                            .addComponent(Bowler_5)
                            .addComponent(Bowler_6)
                            .addComponent(Bowler_7)
                            .addComponent(Bowler_8))
                        .addGap(61, 61, 61)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Over_1)
                            .addComponent(Over_2)
                            .addComponent(Over_3)
                            .addComponent(Over_4)
                            .addComponent(Over_5)
                            .addComponent(Over_6)
                            .addComponent(Over_7)
                            .addComponent(Over_8))
                        .addGap(57, 57, 57)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(RG_8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Wicket_8))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(RG_7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Wicket_7))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(RG_6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Wicket_6))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(RG_5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Wicket_5))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(RG_4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Wicket_4))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(RG_3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Wicket_3))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(RG_2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Wicket_2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(RG_1)
                                .addGap(61, 61, 61)
                                .addComponent(Wicket_1)))
                        .addGap(59, 59, 59)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Eco_6)
                            .addComponent(Eco_7)
                            .addComponent(Eco_8)
                            .addComponent(Eco_1)
                            .addComponent(Eco_2)
                            .addComponent(Eco_3)
                            .addComponent(Eco_4)
                            .addComponent(Eco_5))))
                .addContainerGap(223, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel49)
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bowler_1)
                    .addComponent(Over_1)
                    .addComponent(RG_1)
                    .addComponent(Wicket_1)
                    .addComponent(Eco_1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bowler_2)
                    .addComponent(Over_2)
                    .addComponent(RG_2)
                    .addComponent(Wicket_2)
                    .addComponent(Eco_2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bowler_3)
                    .addComponent(Over_3)
                    .addComponent(RG_3)
                    .addComponent(Wicket_3)
                    .addComponent(Eco_3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bowler_4)
                    .addComponent(Over_4)
                    .addComponent(RG_4)
                    .addComponent(Wicket_4)
                    .addComponent(Eco_4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bowler_5)
                    .addComponent(Over_5)
                    .addComponent(RG_5)
                    .addComponent(Wicket_5)
                    .addComponent(Eco_5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bowler_6)
                    .addComponent(Over_6)
                    .addComponent(RG_6)
                    .addComponent(Wicket_6)
                    .addComponent(Eco_6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bowler_7)
                    .addComponent(Over_7)
                    .addComponent(RG_7)
                    .addComponent(Wicket_7)
                    .addComponent(Eco_7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bowler_8)
                    .addComponent(Over_8)
                    .addComponent(RG_8)
                    .addComponent(Wicket_8)
                    .addComponent(Eco_8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "4's", "6's", "Runs", "Balls", "S. Rate"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        jLabel50.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel50.setText("BATTING STATS");

        Batsman_1.setText("Batsman 1");

        Batsman_2.setText("Batsman 2");

        Batsman_3.setText("Batsman 3");

        Batsman_4.setText("Batsman 4");

        Four_1.setText("0");

        Six_1.setText("0");

        RunS_1.setText("0");

        Ball_1.setText("0");

        Str_1.setText("0");

        Str_2.setText("0");

        Str_3.setText("0");

        Str_4.setText("0");

        Str_5.setText("0");

        Str_6.setText("0");

        Str_7.setText("0");

        Str_8.setText("0");

        Str_9.setText("0");

        Str_10.setText("0");

        Str_11.setText("0");

        Ball_11.setText("0");

        Ball_10.setText("0");

        Ball_9.setText("0");

        Ball_8.setText("0");

        Ball_7.setText("0");

        Ball_6.setText("0");

        Ball_5.setText("0");

        Ball_4.setText("0");

        Ball_3.setText("0");

        Ball_2.setText("0");

        RunS_2.setText("0");

        RunS_3.setText("0");

        RunS_4.setText("0");

        RunS_5.setText("0");

        RunS_6.setText("0");

        RunS_7.setText("0");

        RunS_8.setText("0");

        RunS_9.setText("0");

        RunS_10.setText("0");

        RunS_11.setText("0");

        Six_11.setText("0");

        Six_10.setText("0");

        Six_9.setText("0");

        Six_8.setText("0");

        Six_7.setText("0");

        Six_6.setText("0");

        Six_5.setText("0");

        Six_4.setText("0");

        Six_3.setText("0");

        Six_2.setText("0");

        Four_2.setText("0");

        Four_3.setText("0");

        Four_4.setText("0");

        Four_5.setText("0");

        Four_6.setText("0");

        Four_7.setText("0");

        Four_8.setText("0");

        Four_9.setText("0");

        Four_10.setText("0");

        Four_11.setText("0");

        Batsman_11.setText("Batsman 11");

        Batsman_10.setText("Batsman 10");

        Batsman_9.setText("Batsman 9");

        Batsman_8.setText("Batsman 8");

        Batsman_7.setText("Batsman 7");

        Batsman_6.setText("Batsman 6");

        Batsman_5.setText("Batsman 5");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(jLabel50))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Batsman_1)
                                    .addComponent(Batsman_2)
                                    .addComponent(Batsman_3)
                                    .addComponent(Batsman_4)
                                    .addComponent(Batsman_5)
                                    .addComponent(Batsman_6)
                                    .addComponent(Batsman_7)
                                    .addComponent(Batsman_8)
                                    .addComponent(Batsman_9)
                                    .addComponent(Batsman_10)
                                    .addComponent(Batsman_11))
                                .addGap(83, 83, 83)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Four_1)
                                    .addComponent(Four_2)
                                    .addComponent(Four_3)
                                    .addComponent(Four_4)
                                    .addComponent(Four_5)
                                    .addComponent(Four_6)
                                    .addComponent(Four_7)
                                    .addComponent(Four_8)
                                    .addComponent(Four_9)
                                    .addComponent(Four_10)
                                    .addComponent(Four_11))
                                .addGap(78, 78, 78)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(Six_11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(RunS_11))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(Six_10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(RunS_10))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(Six_9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(RunS_9))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(Six_8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(RunS_8))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(Six_7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(RunS_7))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(Six_6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(RunS_6))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(Six_5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(RunS_5))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(Six_4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(RunS_4))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(Six_3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(RunS_3))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(Six_2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(RunS_2))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(Six_1)
                                        .addGap(83, 83, 83)
                                        .addComponent(RunS_1)))
                                .addGap(71, 71, 71)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Ball_1)
                                    .addComponent(Ball_2)
                                    .addComponent(Ball_3)
                                    .addComponent(Ball_4)
                                    .addComponent(Ball_5)
                                    .addComponent(Ball_6)
                                    .addComponent(Ball_7)
                                    .addComponent(Ball_8)
                                    .addComponent(Ball_9)
                                    .addComponent(Ball_10)
                                    .addComponent(Ball_11))
                                .addGap(68, 68, 68)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Str_11)
                                    .addComponent(Str_10)
                                    .addComponent(Str_9)
                                    .addComponent(Str_8)
                                    .addComponent(Str_2)
                                    .addComponent(Str_1)
                                    .addComponent(Str_7)
                                    .addComponent(Str_6)
                                    .addComponent(Str_5)
                                    .addComponent(Str_4)
                                    .addComponent(Str_3)))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel50)
                .addGap(20, 20, 20)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Batsman_1)
                    .addComponent(Four_1)
                    .addComponent(Six_1)
                    .addComponent(RunS_1)
                    .addComponent(Ball_1)
                    .addComponent(Str_1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Batsman_2)
                    .addComponent(Four_2)
                    .addComponent(Six_2)
                    .addComponent(RunS_2)
                    .addComponent(Ball_2)
                    .addComponent(Str_2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Batsman_3)
                    .addComponent(Four_3)
                    .addComponent(Six_3)
                    .addComponent(RunS_3)
                    .addComponent(Ball_3)
                    .addComponent(Str_3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Batsman_4)
                    .addComponent(Four_4)
                    .addComponent(Six_4)
                    .addComponent(RunS_4)
                    .addComponent(Ball_4)
                    .addComponent(Str_4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Batsman_5)
                    .addComponent(Four_5)
                    .addComponent(Six_5)
                    .addComponent(RunS_5)
                    .addComponent(Ball_5)
                    .addComponent(Str_5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Batsman_6)
                    .addComponent(Four_6)
                    .addComponent(Six_6)
                    .addComponent(RunS_6)
                    .addComponent(Ball_6)
                    .addComponent(Str_6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Batsman_7)
                    .addComponent(Four_7)
                    .addComponent(Six_7)
                    .addComponent(RunS_7)
                    .addComponent(Ball_7)
                    .addComponent(Str_7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Batsman_8)
                    .addComponent(Four_8)
                    .addComponent(Six_8)
                    .addComponent(RunS_8)
                    .addComponent(Ball_8)
                    .addComponent(Str_8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Batsman_9)
                    .addComponent(Four_9)
                    .addComponent(Six_9)
                    .addComponent(RunS_9)
                    .addComponent(Ball_9)
                    .addComponent(Str_9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Batsman_10)
                    .addComponent(Four_10)
                    .addComponent(Six_10)
                    .addComponent(RunS_10)
                    .addComponent(Ball_10)
                    .addComponent(Str_10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Batsman_11)
                    .addComponent(Four_11)
                    .addComponent(Six_11)
                    .addComponent(RunS_11)
                    .addComponent(Ball_11)
                    .addComponent(Str_11))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel51)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel51)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(12, 12, 12))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    static int Score=0, wicket=0, ball=0, over=0, score=0, ball_lef=0;
    String score_temp;
    
    public void run()
    {
        if(JOptionPane.showConfirmDialog(null,"Any run Scored?")==0)
        {
           score_temp=JOptionPane.showInputDialog("Runs:- ");
            score=Integer.parseInt(score_temp);
        }
        else
        {
            score=0;
        }
    }
    
    public void Option()
    {
        if(JOptionPane.showConfirmDialog(null,"Any run Scored?")==0)
        {
           score_temp=JOptionPane.showInputDialog("Runs:- ");
            score=Integer.parseInt(score_temp);
        }
        else
        {
            score=0;
        }
        if(JOptionPane.showConfirmDialog(null,"Any Runouts?")==0)
        {
            wicket++;
        }
        else{
            wicket+=0;
        }
    }
    
    public void over()
    {
        over=ball/6;
        ball_lef=ball%6; 
    }
    
    public void scorecard()
    {
        Current_run.setText(String.valueOf(Score));
        Current_wicket.setText(String.valueOf(wicket));
        Current_over.setText(String.valueOf(over));
        Current_balls.setText(String.valueOf(ball_lef));
    }
    
    private void DotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DotMouseClicked
        Score+=0;
        wicket+=0;
        ball+=1;
        over();
        scorecard();
    }//GEN-LAST:event_DotMouseClicked

    private void Run_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Run_1MouseClicked
        Score+=1;
        wicket+=0;
        ball+=1;
        over();
        scorecard();
    }//GEN-LAST:event_Run_1MouseClicked

    private void Run_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Run_2MouseClicked
        Score+=2;
        wicket+=0;
        ball+=1;
        over();
        scorecard();
    }//GEN-LAST:event_Run_2MouseClicked
   
    private void BowledMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BowledMouseClicked
        Score+=0;
        wicket+=1;
        ball+=1;
        over();
        scorecard();
    }//GEN-LAST:event_BowledMouseClicked

    private void WideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WideMouseClicked
        Score+=1;
        wicket+=0;
        ball+=0;
        over();
        scorecard();
    }//GEN-LAST:event_WideMouseClicked

    private void Wide_moreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Wide_moreMouseClicked
        Option();
        Score+=score+1;
        ball+=0;
        score=0;
        over();
        scorecard();
    }//GEN-LAST:event_Wide_moreMouseClicked

    private void RunoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RunoutMouseClicked
        run();
        Score+=score;
        ball+=1;
        wicket+=1;
        score=0;
        over();
        scorecard();
    }//GEN-LAST:event_RunoutMouseClicked

    private void NoBallMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NoBallMouseClicked
        ball+=0;
        Score+=1;
        wicket+=0;
        over();
        scorecard();
    }//GEN-LAST:event_NoBallMouseClicked

    private void NoBall_moreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NoBall_moreMouseClicked
      Option();
      ball+=0;
      Score+=1+score;
      score=0;
      over();
      scorecard();
    }//GEN-LAST:event_NoBall_moreMouseClicked

    private void HitWicketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HitWicketMouseClicked
        ball+=1;
        wicket+=1;
        Score+=0;
        over();
        scorecard();
    }//GEN-LAST:event_HitWicketMouseClicked

    private void Run_4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Run_4MouseClicked
         ball+=1;
        wicket+=0;
        Score+=4;
        over();
        scorecard();
    }//GEN-LAST:event_Run_4MouseClicked

    private void Run_6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Run_6MouseClicked
        ball+=1;
        wicket+=0;
        Score+=6;
        over();
        scorecard();
    }//GEN-LAST:event_Run_6MouseClicked

    private void Run_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Run_3MouseClicked
       ball+=1;
        wicket+=0;
        Score+=3;
        over();
        scorecard();
    }//GEN-LAST:event_Run_3MouseClicked

    private void LBWMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LBWMouseClicked
        ball+=1;
        wicket+=1;
        Score+=0;
        over();
        scorecard();
    }//GEN-LAST:event_LBWMouseClicked

    private void Bye_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bye_1MouseClicked
        ball+=1;
        wicket+=0;
        Score+=1;
        over();
        scorecard();
    }//GEN-LAST:event_Bye_1MouseClicked

    private void Bye_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bye_2MouseClicked
        ball+=1;
        wicket+=0;
        Score+=2;
        over();
        scorecard();
    }//GEN-LAST:event_Bye_2MouseClicked

    private void Bye_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bye_3MouseClicked
        ball+=1;
        wicket+=0;
        Score+=3;
        over();
        scorecard();
    }//GEN-LAST:event_Bye_3MouseClicked

    private void Bye_4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bye_4MouseClicked
        ball+=1;
        wicket+=0;
        Score+=4;
        over();
        scorecard();
    }//GEN-LAST:event_Bye_4MouseClicked

    private void Caught_outMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Caught_outMouseClicked
        run();
        ball+=1;
        wicket+=1;
        Score+=score;
        score=0;
        over();
        scorecard();
    }//GEN-LAST:event_Caught_outMouseClicked

    private void LBye_0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LBye_0MouseClicked
      ball+=1;
        wicket+=0;
        Score+=0;
        over();
        scorecard();
    }//GEN-LAST:event_LBye_0MouseClicked

    private void LBye_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LBye_1MouseClicked
       ball+=1;
        wicket+=0;
        Score+=1;
        over();
        scorecard();
    }//GEN-LAST:event_LBye_1MouseClicked

    private void LBye_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LBye_2MouseClicked
        ball+=1;
        wicket+=0;
        Score+=2;
        over();
        scorecard();
    }//GEN-LAST:event_LBye_2MouseClicked

    private void LBye_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LBye_3MouseClicked
        ball+=1;
        wicket+=0;
        Score+=3;
        over();
        scorecard();
    }//GEN-LAST:event_LBye_3MouseClicked

    private void LBye_4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LBye_4MouseClicked
       ball+=1;
        wicket+=0;
        Score+=4;
        over();
        scorecard();
    }//GEN-LAST:event_LBye_4MouseClicked

    private void StumpedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StumpedMouseClicked
        ball+=1;
        wicket+=1;
        Score+=0;
        over();
        scorecard();
    }//GEN-LAST:event_StumpedMouseClicked

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaveActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Scorecard1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Scorecard1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Scorecard1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Scorecard1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Scorecard1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Ball_1;
    private javax.swing.JLabel Ball_10;
    private javax.swing.JLabel Ball_11;
    private javax.swing.JLabel Ball_2;
    private javax.swing.JLabel Ball_3;
    private javax.swing.JLabel Ball_4;
    private javax.swing.JLabel Ball_5;
    private javax.swing.JLabel Ball_6;
    private javax.swing.JLabel Ball_7;
    private javax.swing.JLabel Ball_8;
    private javax.swing.JLabel Ball_9;
    private javax.swing.JLabel Batsman_1;
    private javax.swing.JLabel Batsman_10;
    private javax.swing.JLabel Batsman_11;
    private javax.swing.JLabel Batsman_2;
    private javax.swing.JLabel Batsman_3;
    private javax.swing.JLabel Batsman_4;
    private javax.swing.JLabel Batsman_5;
    private javax.swing.JLabel Batsman_6;
    private javax.swing.JLabel Batsman_7;
    private javax.swing.JLabel Batsman_8;
    private javax.swing.JLabel Batsman_9;
    private javax.swing.JLabel Batsman_A;
    private javax.swing.JLabel Batsman_B;
    private javax.swing.JLabel Bowled;
    private javax.swing.JLabel Bowler_1;
    private javax.swing.JLabel Bowler_2;
    private javax.swing.JLabel Bowler_3;
    private javax.swing.JLabel Bowler_4;
    private javax.swing.JLabel Bowler_5;
    private javax.swing.JLabel Bowler_6;
    private javax.swing.JLabel Bowler_7;
    private javax.swing.JLabel Bowler_8;
    private javax.swing.JLabel Bye_1;
    private javax.swing.JLabel Bye_2;
    private javax.swing.JLabel Bye_3;
    private javax.swing.JLabel Bye_4;
    private javax.swing.JLabel Caught_out;
    private javax.swing.JLabel Current_balls;
    private javax.swing.JLabel Current_over;
    private javax.swing.JLabel Current_run;
    private javax.swing.JLabel Current_wicket;
    private javax.swing.JLabel Dot;
    private javax.swing.JLabel Eco_1;
    private javax.swing.JLabel Eco_2;
    private javax.swing.JLabel Eco_3;
    private javax.swing.JLabel Eco_4;
    private javax.swing.JLabel Eco_5;
    private javax.swing.JLabel Eco_6;
    private javax.swing.JLabel Eco_7;
    private javax.swing.JLabel Eco_8;
    private javax.swing.JLabel Four_1;
    private javax.swing.JLabel Four_10;
    private javax.swing.JLabel Four_11;
    private javax.swing.JLabel Four_2;
    private javax.swing.JLabel Four_3;
    private javax.swing.JLabel Four_4;
    private javax.swing.JLabel Four_5;
    private javax.swing.JLabel Four_6;
    private javax.swing.JLabel Four_7;
    private javax.swing.JLabel Four_8;
    private javax.swing.JLabel Four_9;
    private javax.swing.JLabel HitWicket;
    private javax.swing.JLabel LBW;
    private javax.swing.JLabel LBye_0;
    private javax.swing.JLabel LBye_1;
    private javax.swing.JLabel LBye_2;
    private javax.swing.JLabel LBye_3;
    private javax.swing.JLabel LBye_4;
    private javax.swing.JLabel NoBall;
    private javax.swing.JLabel NoBall_more;
    private javax.swing.JLabel Over_1;
    private javax.swing.JLabel Over_2;
    private javax.swing.JLabel Over_3;
    private javax.swing.JLabel Over_4;
    private javax.swing.JLabel Over_5;
    private javax.swing.JLabel Over_6;
    private javax.swing.JLabel Over_7;
    private javax.swing.JLabel Over_8;
    private javax.swing.JLabel RG_1;
    private javax.swing.JLabel RG_2;
    private javax.swing.JLabel RG_3;
    private javax.swing.JLabel RG_4;
    private javax.swing.JLabel RG_5;
    private javax.swing.JLabel RG_6;
    private javax.swing.JLabel RG_7;
    private javax.swing.JLabel RG_8;
    private javax.swing.JLabel RunS_1;
    private javax.swing.JLabel RunS_10;
    private javax.swing.JLabel RunS_11;
    private javax.swing.JLabel RunS_2;
    private javax.swing.JLabel RunS_3;
    private javax.swing.JLabel RunS_4;
    private javax.swing.JLabel RunS_5;
    private javax.swing.JLabel RunS_6;
    private javax.swing.JLabel RunS_7;
    private javax.swing.JLabel RunS_8;
    private javax.swing.JLabel RunS_9;
    private javax.swing.JLabel Run_1;
    private javax.swing.JLabel Run_2;
    private javax.swing.JLabel Run_3;
    private javax.swing.JLabel Run_4;
    private javax.swing.JLabel Run_6;
    private javax.swing.JLabel Runout;
    private javax.swing.JButton Save;
    private javax.swing.JLabel Six_1;
    private javax.swing.JLabel Six_10;
    private javax.swing.JLabel Six_11;
    private javax.swing.JLabel Six_2;
    private javax.swing.JLabel Six_3;
    private javax.swing.JLabel Six_4;
    private javax.swing.JLabel Six_5;
    private javax.swing.JLabel Six_6;
    private javax.swing.JLabel Six_7;
    private javax.swing.JLabel Six_8;
    private javax.swing.JLabel Six_9;
    private javax.swing.JLabel Str_1;
    private javax.swing.JLabel Str_10;
    private javax.swing.JLabel Str_11;
    private javax.swing.JLabel Str_2;
    private javax.swing.JLabel Str_3;
    private javax.swing.JLabel Str_4;
    private javax.swing.JLabel Str_5;
    private javax.swing.JLabel Str_6;
    private javax.swing.JLabel Str_7;
    private javax.swing.JLabel Str_8;
    private javax.swing.JLabel Str_9;
    private javax.swing.JLabel Stumped;
    private javax.swing.JLabel Wicket_1;
    private javax.swing.JLabel Wicket_2;
    private javax.swing.JLabel Wicket_3;
    private javax.swing.JLabel Wicket_4;
    private javax.swing.JLabel Wicket_5;
    private javax.swing.JLabel Wicket_6;
    private javax.swing.JLabel Wicket_7;
    private javax.swing.JLabel Wicket_8;
    private javax.swing.JLabel Wide;
    private javax.swing.JLabel Wide_more;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
